spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 1
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  data:
    mongodb:
      uri: mongodb://root:123456789@localhost:27017
      database: db_notify

otel:
  traces:
    exporter: otlp #otlp / zipkin / console / logging-otlp / none
  metrics:
    exporter: none #otlp / prometheus / none
  logs:
    exporter: none #otlp / console / logging-otlp / none
  exporter:
    otlp:
      traces:
        protocol: grpc
        endpoint: http://localhost:4317