spring:
  application:
    name: service-inventory

server:
  port: 8080

management:
  endpoints:
    web:
      base-path: '/services-inventory/actuator'
      exposure:
        include: "*"
  health:
    show-details: always
    probes:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
