global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'services-order'
    metrics_path: 'services-order/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8081']
  - job_name: 'services-inventory'
    metrics_path: 'services-inventory/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082']
  - job_name: 'services-notify'
    metrics_path: 'services-notify/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]