receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

processors:
  batch:

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

  debug:
    verbosity: detailed

  zipkin:
    endpoint: "http://host.docker.internal:9411/api/v2/spans"
    format: proto

  otlp/jaeger:
    endpoint: "http://host.docker.internal:4319"
    tls:
      insecure: true

#  loki:
#    endpoint: "http://localhost:3100/loki/api/v1/push"

#  otp:
#    endpoint: tempo:4317
#    tls:
#      insecure: true
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin, otlp/jaeger]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]
    #logs:
      #receivers: [otlp]
      ##processors: [batch]
      #exporters: [loki]