# Scale Horizontal pod
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: services-inventory-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: services-inventory-deploy
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50